# Site settings
title: RIT Linux Users Group
email: ngl3477@rit.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: 'http://ritlug.github.io'
# Build settings
markdown: kramdown
