# Site settings
title: RIT Linux Users Group
email: ngl3477@rit.edu
description: > # this means to ignore newlines until "baseurl:"
  Official site of the RIT Linux Users Group (RITlug). Find all
  our talks and announcements here.

url: 'http://ritlug.github.io'
# Build settings
markdown: kramdown
