# Site settings
title: Brown Open Source Club
title-abbrev: BrownOS

email: brownos@brown.edu
description: > # this means to ignore newlines until "baseurl:"
  Official site of the Brown Open Source Club (BrownOS). Find all
  our talks and announcements here.

url: 'https://brownos.github.io/'
# Build settings
markdown: kramdown

# These allow RITlug's schedule to be updated site-wide from one
# location. They will appear in pages as they are typed, so it
# is recommended that you follow the format already here when
# updating them.
ritlug-time: 4:00PM - 6:00PM
ritlug-place: CIT???
ritlug-day: Friday
